workflows:
  android_apk:
    name: Expo Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        EXPO_NO_TELEMETRY: "1"
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build Android APK with EAS
        script: |
          # Requires an Expo account and EAS project setup.
          # First time, you may need: eas init
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - $HOME/.eas/builds/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com

  web_export:
    name: Expo Web Export (static)
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      vars:
        EXPO_NO_TELEMETRY: "1"
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Export web build
        script: |
          npx expo export --platform web
    artifacts:
      - dist/**

  ios_build_placeholder:
    name: iOS build (needs signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        EXPO_NO_TELEMETRY: "1"
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build iOS with EAS
        script: |
          # This will fail unless you add Apple credentials in Codemagic/EAS.
          eas build --platform ios --profile preview --non-interactive
    artifacts:
      - $HOME/.eas/builds/**/*.ipa
